### PR TITLE
Replace ApplePS2SmartTouchpad with VoodoPS2

### PR DESCRIPTION
**Pull request by BAndysc**
With proper support for multitouch gestures for ELAN PS/2 Touchpads

let me know if it works for you

### CODE REVIEW

**Comment by danang-id** [comment]
Where have you done your research about ELAN PS/2 support?

This obviously **will not work**. Acidanthera's VoodooPS2 is not compatible with ELAN PS/2 touchpad. It has been mentioned by vit9696 that VoodooPS2 will not be supporting ELAN PS/2. The main reason was because the new ELAN kext (ApplePS2SmartTouchpad kext) is not open sourced by EMlyDinEsHMG, hereby no one can contribute nor put the code into VoodooPS2, so a rework should be done for VoodooPS2 to support ELAN PS/2.

https://github.com/acidanthera/bugtracker/issues/488#issuecomment-583771250

**Comment by BAndysc** [comment]
https://github.com/BAndysc/VoodooPS2/tree/elanps2
This is fork with elan support via VoodooInput which means native macOS gestures

**Comment by danang-id** [comment]
I see. You should let me know that this was your fork of VoodooPS2. 

Alright, I'm going to test it.

**Comment by danang-id** [comment]
@BAndysc I have compiled your fork of VoodooPS2 and tested on my machine. The result was the same as the original VoodoPS2. It was not detected as a trackpad nor it emulate the trackpad as well. The behavior was the same, when I tried to move the cursor using the trackpad, the cursor start to jump around the screen randomly.

[Screenshot](https://i.postimg.cc/VNJDRVcm/Screenshot-2020-07-29-at-11-19-34.png)

**Comment by BAndysc** [comment]
That's weird, all ps2 elan devices should be supported. Would you like to debug it with me? If so, you ca contact me via discord bandysc#5087

**Comment by danang-id** [comment]
@BAndysc Thanks, I really would love to. But, I'm not sure if I will have time to do it this month. Would it be okay to contact you later this month?

**Pull request closed without merging**
